services:
  app:
    container_name: inethi-backend
    restart: unless-stopped
    env_file:
      - ./.env
    build:
      context: .
      args:
        - DEV=${DEV:-false}
    ports:
      - "8000:8000"
    volumes:
      - ./inethi:/inethi
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              gunicorn inethi.wsgi:application --bind 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-devdb}
      - DB_USER=${DB_USER:-devuser}
      - DB_PASS=${DB_PASS:-devpass}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.inethicloud.net`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

  db:
    image: postgres:16.4-alpine
    restart: unless-stopped
    container_name: inethi-backend-db
    env_file:
      - ./.env
    volumes:
      - prod-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-devdb}
      - POSTGRES_USER=${DB_USER:-devuser}
      - POSTGRES_PASSWORD=${DB_PASS:-devpass}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backenddb.entrypoints=websecure"


networks:
  default:
    external:
      name: "inethi-bridge-traefik"

volumes:
  prod-db-data: