services:
  app:
    container_name: inethi-backend
    restart: unless-stopped
    env_file:
      - ./.env
    build:
      context: .
      args:
        - DEV=${DEV:-true}
    ports:
      - "8000:8000"
    volumes:
      - ./inethi:/inethi
    command: >
      sh -c "python manage.py wait_for_db &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-devdb}
      - DB_USER=${DB_USER:-devuser}
      - DB_PASS=${DB_PASS:-devpass}
    depends_on:
      - db
      - keycloak

  db:
    image: postgres:16.4-alpine
    restart: unless-stopped
    container_name: inethi-backend-db
    env_file:
      - ./.env
    volumes:
      - dev-db-data:/var/lib/postgresql/data
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - POSTGRES_DB=${DB_NAME:-devdb}
      - POSTGRES_USER=${DB_USER:-devuser}
      - POSTGRES_PASSWORD=${DB_PASS:-devpass}

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    restart: unless-stopped
    container_name: inethi-keycloak
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - dev-keycloak-data:/opt/keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-devuser}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD:-devpass}

volumes:
  dev-db-data:
  dev-keycloak-data: