services:
  app:
    container_name: inethi-backend-dev
    restart: no
    env_file:
      - ./.env
    build:
      context: .
      args:
        - DEV=${DEV:-true}
    ports:
      - "8000:8000"
    volumes:
      - ./inethi:/inethi
    command: >
      sh -c "sleep 10 &&
              python manage.py wait_for_db &&
              python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=${DB_HOST:-db}
      - DB_NAME=${DB_NAME:-devdb}
      - DB_USER=${DB_USER:-devuser}
      - DB_PASS=${DB_PASS:-devpass}
    depends_on:
      - db
      - keycloak

  db:
    image: timescale/timescaledb:latest-pg17
    restart: no
    container_name: inethi-backend-db-timescale-dev
    env_file:
      - ./.env
    volumes:
      - dev-db-data-timescale-dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-devdb}
      - POSTGRES_USER=${DB_USER:-devuser}
      - POSTGRES_PASSWORD=${DB_PASS:-devpass}
    command: postgres -c shared_preload_libraries=timescaledb

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    restart: no
    container_name: inethi-keycloak-dev
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command:
      - start-dev
    volumes:
      - dev-keycloak-data-dev:/opt/keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_MASTER_ADMIN:-devuser}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_MASTER_ADMIN_PASSWORD:-devpass}

  redis:
    image: redis:alpine
    restart: no
    container_name: inethi-backend-celery-redis-dev

  celery:
    build:
      context: .
    env_file:
      - ./.env
    restart: no
    command: celery -A inethi worker -l INFO
    volumes:
      - ./inethi:/inethi
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    container_name: inethi-backend-celery-dev
    depends_on:
      - redis
      - db
  celery_beat:
    build:
      context: .
    env_file:
      - ./.env
    command: celery -A inethi beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: no
    volumes:
      - ./inethi:/inethi
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    container_name: inethi-backend-celery-beat-dev
    depends_on:
      - redis
      - db

volumes:
  dev-db-data-timescale-dev:
  dev-keycloak-data-dev:
