---
name: Checks

on: [push]

jobs:
  lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo "DEV=true" >> .env
          echo "DB_HOST=db" >> .env
          echo "DB_NAME=devdb" >> .env
          echo "DB_USER=devuser" >> .env
          echo "DB_PASS=devpass" >> .env
          echo "KEYCLOAK_ADMIN=devuser" >> .env
          echo "KEYCLOAK_ADMIN_PASSWORD=devpass" >> .env
          echo "KEYCLOAK_URL=http://localhost:8080" >> .env
          echo "KEYCLOAK_REALM=example" >> .env
          echo "KEYCLOAK_BACKEND_CLIENT_ID=backend" >> .env
          echo "KEYCLOAK_CLIENT_SECRET=secret" >> .env
          echo "KEYCLOAK_FRONTEND_CLIENT_ID=inethi-frontend-client" >> .env
          echo "KEYCLOAK_ADMIN_USERNAME=admin" >> .env
          echo "WALLET_ENCRYPTION_KEY=fY6coDOzzi2NonOA2rdPI2f-a_MLie8oafZX5XgtZw4=" >> .env # this is a placeholder and not used...
          echo "BLOCKCHAIN_PROVIDER_URL=https://forno.celo.org" >> .env
          echo "CONTRACT_ADDRESS=0x8Bab657c88eb3c724486D113E650D2c659aa23d2" >> .env
          echo "REGISTRY_ADDRESS=0x9b1a3F8FadD0dc86FBae5Cf66Fa682fDcd84a9b0" >> .env
          echo "FAUCET_ADDRESS=0xB821E49ADB53F0AbeD834278d5dFc57901c30Eea" >> .env
          echo "ACCOUNT_INDEX_ADMIN_WALLET_ADDRESS=<SMART_CONTRACT_CREATOR>" >> .env
          echo "FAUCET_AND_INDEX_ENABLED=True" >> .env
          echo "FAUCET_ADMIN_WALLET_ADDRESS=<SMART_CONTRACT_CREATOR>" >> .env
      - name: Lint
        run: docker compose -f docker-compose-dev.yml run --rm app sh -c "flake8"
      - name: Tests
        run: docker compose -f docker-compose-dev.yml run --rm app sh -c "python manage.py test"
